name: Update streak stats

on:
  schedule:
    - cron: "0 */6 * * *"  # se regenera cada 6 horas
  workflow_dispatch: {}     # correrlo manualmente desde la pestaña "Actions"
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate streak stats (neon theme)
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          options: user=${{ github.repository_owner }}&hide_border=true&background=060606&ring=39FF14&fire=FF00FF&currStreakLabel=00FFF2&sideNums=00FFF2&dates=7a7a7a&stroke=000000
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push
